# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShowcaseSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for ShowcaseSample
  #pod 'Showcase' , :git => 'http://bellatrix:8080/tfs/ArgeMimariCollection/OneFrameIOS/_git/Showcase', :tag => '1.1.0'
  pod 'Showcase' , :path => '/Users/a02484320/Desktop/Showcase'
end


target 'ShowcaseSampleUITests' do
  inherit! :search_paths
  # Pods for testing
  pod 'Showcase' , :path => '/Users/a02484320/Desktop/Showcase'
end

